### ISSUE TITLE
Assignment 5-4

### ISSUE THREAD

**Issue by ambethia** [utumno86/Assignments#26]
# Week 5 - Day 4

## Part I

Fork the `todos-cli` repo we worked on this afternoon and complete it's implementation accordning to the `README`:

  https://github.com/tiy-tpa-rails-q2-2015/todos-cli

## Part II

Create a Rails app that has the same features as your CLI todo app.

- [x] Include all the functionality from your CLI todo app's README.
- [x] Deploy to heroku, put some lists up on heroku for me to look at.
- [x] Use Foundation or Bootstrap to make it look nice.
- [x] No scaffolding!
- [x] Link me both your app's repository and deployed Heroku app before you close out the issue.

** Bonus ** 

- [ ] Add User authentication (hand rolled, or checkout `devise`), make lists belong to the user who's logged in. That use should only see their own lists.

**Comment by utumno86** [comment]
The straight ruby version isn't beautiful, but it's functional and fulfills all the requirements. https://github.com/utumno86/todos-cli   Now to start on the rails app portion.

**Comment by utumno86** [comment]
Not even close to finished with the rails app, but I'm planning to watch Game of Thrones and go to bed so I can be functional tomorrow, so here's what I got: https://github.com/utumno86/todolist

**Comment by utumno86** [comment]
Works like a charm on heroku. That makes three successful heroku deploys, first try, no problem https://todos-86.herokuapp.com/

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/sMz807CVPNpS/200w_d.gif)
